services:
    factrine:
        class: BiteCodes\FactrineBundle\Factory\Factory
        arguments:
            - '@factrine.entity_builder'
            - '@factrine.util.value_factory'
            - '@factrine.util.persistence_helper'

    factrine.entity_builder:
        class: BiteCodes\FactrineBundle\Factory\EntityBuilder\EntityBuilder
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@factrine.config_provider.yaml_config_provider'

    factrine.config_provider.config_loader:
        class: BiteCodes\FactrineBundle\Factory\ConfigProvider\ConfigLoader
        public: false
        arguments: [{}]

    factrine.config_provider.config_generator:
        class: BiteCodes\FactrineBundle\Factory\ConfigProvider\ConfigGenerator
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@factrine.util.data_guesser'
            - '@kernel'

    factrine.config_provider.yaml_config_provider:
        class: BiteCodes\FactrineBundle\Factory\ConfigProvider\YamlConfigProvider
        public: false
        arguments:
            - '@factrine.config_provider.config_loader'

    factrine.data_provider.faker_data_provider:
        class: BiteCodes\FactrineBundle\Factory\DataProvider\FakerDataProvider
        public: false

    factrine.util.value_factory:
        class: BiteCodes\FactrineBundle\Factory\Util\ValueFactory
        public: false
        arguments:
            - '@factrine.config_provider.yaml_config_provider'
            - ['@factrine.data_provider.faker_data_provider']

    factrine.util.data_guesser:
        class: BiteCodes\FactrineBundle\Factory\Util\DataGuesser
        public: false
        arguments:
            - '@factrine.data_provider.faker_data_provider'

    factrine.util.persistence_helper:
        class: BiteCodes\FactrineBundle\Factory\Util\PersistenceHelper
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'

    # Commands

    factrine.command.seed:
        class: BiteCodes\FactrineBundle\Command\FactrineSeedCommand
        arguments:
            - '@factrine'
            - %kernel.root_dir%/seeds/
        tags:
            -  { name: console.command }

    factrine.command.seed_entity:
        class: BiteCodes\FactrineBundle\Command\FactrineSeedEntityCommand
        arguments:
            - '@factrine'
            - '@doctrine.orm.entity_manager'
        tags:
            -  { name: console.command }

    bite_codes.command.generate_files:
        class: BiteCodes\FactrineBundle\Command\FactrineGenerateFilesCommand
        arguments:
            - '@factrine.config_provider.config_generator'
            - '@kernel'
        tags:
            - { name: console.command }
