language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - mkdir -p build/logs

install: composer update --prefer-dist

after_script:
  - php vendor/bin/coveralls
